// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.1.2

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type SweetHTTPServer interface {
	Ping(context.Context, *BaseReq) (*BaseReply, error)
}

func RegisterSweetHTTPServer(s *http.Server, srv SweetHTTPServer) {
	r := s.Route("/")
	r.GET("/ping", _Sweet_Ping0_HTTP_Handler(srv))
}

func _Sweet_Ping0_HTTP_Handler(srv SweetHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in BaseReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/pb.v1.Sweet/Ping")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Ping(ctx, req.(*BaseReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*BaseReply)
		return ctx.Result(200, reply)
	}
}

type SweetHTTPClient interface {
	Ping(ctx context.Context, req *BaseReq, opts ...http.CallOption) (rsp *BaseReply, err error)
}

type SweetHTTPClientImpl struct {
	cc *http.Client
}

func NewSweetHTTPClient(client *http.Client) SweetHTTPClient {
	return &SweetHTTPClientImpl{client}
}

func (c *SweetHTTPClientImpl) Ping(ctx context.Context, in *BaseReq, opts ...http.CallOption) (*BaseReply, error) {
	var out BaseReply
	pattern := "/ping"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation("/pb.v1.Sweet/Ping"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
